[package]
name = "html_template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html_template_core = { path = "../html_template_core" }
html_template_macros = { path = "../html_template_macros" }
